### PR TITLE
Add upcoming events section.

### PR DESCRIPTION
**Pull request by eugener**
Currently 3 conferences are added: 

- OracleCode One
- Devoxx Belgium
- JavaFX Days Zurich

Logo for JavaFX Days is created as a placeholder with agreement from Dirk. He will supply the official one next week.

### CODE REVIEW

**Comment by eugener** [comment]
Thanks! Both good catches. Latest commit fixes both of them.

**Comment by abhinayagarwal** [comment]
There are still 2 events per row. However this can be improved moving forward. For now, I will merge this PR :)

**Comment by eugener** [comment]
I did that on purpose. But that can always be tweaked.
Can you please deploy the latest version of  the site?

**Comment by eugener** [comment]
Thanks! Looks even better IMO

**Pull request merged**
